# -*- coding: utf-8 -*-
"""InvestAI_Stock_Prediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qMnWLAijCsvvcYYZmGEdG0mdCWR2ji6H

# 📈 InvestAI — Sistem Prediksi Saham Indonesia

---

## 🧠 Tentang Project

**InvestAI** adalah sistem prediksi pergerakan saham Indonesia berbasis **Machine Learning**.

Dengan memanfaatkan data historis dari **Yahoo Finance (yfinance)** dan berbagai **indikator teknikal**, model ini mampu memprediksi apakah harga saham akan **Naik 📈** atau **Turun 📉** pada hari berikutnya.

### 🎯 Tujuan Project
- Membangun pipeline ML end-to-end untuk prediksi arah saham
- Mengekstrak sinyal dari indikator teknikal (SMA, EMA, RSI, MACD, dll)
- Memberikan rekomendasi **Bullish / Bearish** beserta **confidence score**
- Simulasi inference real-time untuk demo hackathon

### 📌 Saham yang Dianalisis
| Ticker | Emiten |
|--------|--------|
| BBCA.JK | Bank Central Asia |
| BBRI.JK | Bank Rakyat Indonesia |
| TLKM.JK | Telkom Indonesia |

### 🛠️ Tech Stack
- `yfinance` — data historis saham
- `pandas`, `numpy` — manipulasi data
- `ta` — kalkulasi indikator teknikal
- `xgboost` — model utama
- `scikit-learn` — preprocessing & evaluasi
- `matplotlib`, `plotly` — visualisasi
- `joblib` — save/load model

---
> ⚠️ **Disclaimer:** Notebook ini dibuat untuk tujuan **edukasi dan riset**. Bukan merupakan saran investasi.

---
# 1️⃣ Install & Import Library
"""

# ============================================================
# Install library yang dibutuhkan
# Jalankan cell ini sekali saja
# ============================================================
!pip install yfinance ta xgboost plotly --quiet

# ============================================================
# Import semua library
# ============================================================

# === Data & Numerik ===
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

# === Data Source ===
import yfinance as yf

# === Indikator Teknikal ===
import ta
from ta.trend import SMAIndicator, EMAIndicator, MACD
from ta.momentum import RSIIndicator
from ta.volatility import BollingerBands

# === Machine Learning ===
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score, classification_report,
    confusion_matrix, ConfusionMatrixDisplay
)

# === Visualisasi ===
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots

# === Save Model ===
import joblib
import os
from datetime import datetime, timedelta

print("✅ Semua library berhasil diimport!")
print(f"📅 Waktu eksekusi: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

"""---
# 2️⃣ Konfigurasi & Fetch Data

Kita akan mengambil data historis saham dari **Yahoo Finance** menggunakan library `yfinance`.

Data yang diambil:
- **Open** — harga pembukaan
- **High** — harga tertinggi dalam sehari
- **Low** — harga terendah dalam sehari
- **Close** — harga penutupan (yang paling penting!)
- **Volume** — jumlah lembar saham yang diperdagangkan
"""

import pandas as pd
from datetime import datetime

# ============================================================
# Konfigurasi global project
# ============================================================

TICKERS = [
    # Perbankan & Keuangan
    'BBCA.JK', 'BMRI.JK', 'BBNI.JK', 'BBRI.JK', 'BRIS.JK', 'BTPS.JK',
    'ARTO.JK', 'BNGA.JK', 'NISP.JK', 'BDMN.JK', 'MEGA.JK', 'BJBR.JK',
    # Energi & Pertambangan
    'ADRO.JK', 'PTBA.JK', 'ITMG.JK', 'HRUM.JK', 'BUMI.JK', 'INDY.JK',
    'MDKA.JK', 'ANTM.JK', 'INCO.JK', 'MEDC.JK', 'ELSA.JK', 'PGAS.JK',
    'ESSA.JK', 'ADMR.JK',
    # Consumer Goods & Retail
    'UNVR.JK', 'INDF.JK', 'ICBP.JK', 'KLBF.JK', 'CPIN.JK', 'JPFA.JK',
    'MYOR.JK', 'SIDO.JK', 'GOOD.JK', 'ACES.JK', 'MAPI.JK', 'MAPA.JK', 'ERAA.JK',
    # Telekomunikasi & Teknologi
    'TLKM.JK', 'EXCL.JK', 'ISAT.JK','TOWR.JK', 'TBIG.JK',
    'DCII.JK', 'BUKA.JK', 'GOTO.JK', 'EMTK.JK', 'SCMA.JK',
    # Industri & Manufaktur
    'ASII.JK', 'UNTR.JK', 'SRIL.JK', 'AKRA.JK', 'SMGR.JK', 'INTP.JK',
    'AMFG.JK', 'CTRA.JK', 'BJTM.JK',
    # Properti & Konstruksi
    'LPKR.JK', 'WIKA.JK', 'WSKT.JK', 'PPRE.JK', 'PTPP.JK', 'BSDE.JK',
    'SMRA.JK', 'PWON.JK',
    # Healthcare & Farmasi
    'KAEF.JK', 'PYFA.JK', 'MIKA.JK', 'HEAL.JK', 'TSPC.JK',
    # Infrastruktur & Utilitas
    'JSMR.JK', 'WEGE.JK', 'META.JK', 'BIRD.JK', 'NELY.JK',
    # Agribisnis
    'AALI.JK', 'SIMP.JK', 'LSIP.JK', 'TBLA.JK',
    # Media & Hiburan
    'MNCN.JK', 'VIVA.JK', 'LINK.JK',
    # Logistik & Pergudangan
    'HRTA.JK', 'INTD.JK',
]

START_DATE     = '2020-01-01'
END_DATE       = datetime.today().strftime('%Y-%m-%d')
PRIMARY_TICKER = 'BBCA.JK'

print(f"📌 Total Ticker : {len(TICKERS)} saham")
print(f"📅 Periode      : {START_DATE} → {END_DATE}")
print(f"🎯 Primary      : {PRIMARY_TICKER}")

# ============================================================
# Fungsi untuk mengambil & membersihkan data dari yfinance
# ============================================================

def fetch_stock_data(ticker: str, start: str, end: str) -> pd.DataFrame:
    """
    Mengambil data historis saham dari Yahoo Finance.

    Parameters:
        ticker : kode saham (contoh: 'BBCA.JK')
        start  : tanggal mulai (format 'YYYY-MM-DD')
        end    : tanggal akhir (format 'YYYY-MM-DD')

    Returns:
        DataFrame dengan kolom OHLCV
    """
    print(f"⏳ Mengambil data {ticker}...")
    df = yf.download(ticker, start=start, end=end, progress=False, auto_adjust=True)

    if df.empty:
        print(f"   ❌ Gagal mendapatkan data untuk {ticker}. DataFrame kosong.")
        return pd.DataFrame()

    # Flatten MultiIndex columns jika ada
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)

    # Pastikan kolom yang dibutuhkan ada
    required_cols = ['Open', 'High', 'Low', 'Close', 'Volume']
    df = df[required_cols].copy()
    df.dropna(inplace=True)

    if df.empty:
        print(f"   ❌ Data untuk {ticker} menjadi kosong setelah preprocessing.")
        return pd.DataFrame()

    print(f"   ✅ {ticker}: {len(df)} baris data ({df.index[0].date()} → {df.index[-1].date()})")
    return df


# --- Ambil data semua ticker ---
all_data = {}
for ticker in TICKERS:
    all_data[ticker] = fetch_stock_data(ticker, START_DATE, END_DATE)

# Data utama untuk model
df_raw = all_data[PRIMARY_TICKER].copy()

print(f"\n📊 Preview data {PRIMARY_TICKER}:")
df_raw.head()

"""---
# 3️⃣ Exploratory Data Analysis (EDA)

Sebelum modeling, kita perlu **memahami data** terlebih dahulu.
EDA membantu kita melihat pola, distribusi, dan anomali pada data saham.
"""

# ============================================================
# Statistik deskriptif
# ============================================================

print(f"📊 Statistik Deskriptif — {PRIMARY_TICKER}")
print("=" * 50)
print(f"Jumlah data  : {len(df_raw):,} hari trading")
print(f"Rentang      : {df_raw.index[0].date()} → {df_raw.index[-1].date()}")
print(f"Harga terendah  (Close): Rp {df_raw['Close'].min():,.0f}")
print(f"Harga tertinggi (Close): Rp {df_raw['Close'].max():,.0f}")
print(f"Harga terakhir  (Close): Rp {df_raw['Close'].iloc[-1]:,.0f}")
print(f"Missing values  : {df_raw.isnull().sum().sum()}")
print()
df_raw.describe()

import matplotlib.pyplot as plt
# ============================================================
# Visualisasi harga historis semua ticker (Candlestick-style)
# ============================================================

fig, axes = plt.subplots(len(TICKERS), 1, figsize=(14, 4 * len(TICKERS)), sharex=False)
colors = ['#2196F3', '#4CAF50', '#FF5722']

for i, (ticker, ax) in enumerate(zip(TICKERS, axes)):
    data = all_data[ticker]
    ax.plot(data.index, data['Close'], color=colors[i % len(colors)], linewidth=1.5, label='Close Price')
    ax.fill_between(data.index, data['Close'], alpha=0.1, color=colors[i % len(colors)])
    ax.set_title(f'📈 {ticker} — Harga Penutupan (2020–Now)', fontsize=13, fontweight='bold')
    ax.set_ylabel('Harga (IDR)', fontsize=10)
    ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f'Rp {x:,.0f}'))
    ax.grid(True, alpha=0.3)
    ax.legend(loc='upper left')

plt.tight_layout()
plt.suptitle('Perbandingan Harga Saham Indonesia', fontsize=15, fontweight='bold', y=1.01)
plt.savefig('plot_harga_historis.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ Plot disimpan: plot_harga_historis.png")

# ============================================================
# Distribusi daily return
# ============================================================

fig, axes = plt.subplots(1, len(TICKERS), figsize=(15, 4))

for i, (ticker, ax) in enumerate(zip(TICKERS, axes)):
    returns = all_data[ticker]['Close'].pct_change().dropna() * 100
    ax.hist(returns, bins=60, color=colors[i % len(colors)], alpha=0.7, edgecolor='white')
    ax.axvline(returns.mean(), color='red', linestyle='--', linewidth=1.5, label=f'Mean: {returns.mean():.2f}%')
    ax.set_title(f'{ticker}', fontsize=12, fontweight='bold')
    ax.set_xlabel('Daily Return (%)')
    ax.set_ylabel('Frekuensi')
    ax.legend()
    ax.grid(True, alpha=0.3)

plt.suptitle('📊 Distribusi Daily Return', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

# ============================================================
# Korelasi harga Close antar saham
# ============================================================

# Gabungkan kolom Close dari semua saham
close_all = pd.DataFrame({
    ticker: all_data[ticker]['Close'] for ticker in TICKERS
})

corr_matrix = close_all.corr()

fig, ax = plt.subplots(figsize=(6, 5))
im = ax.imshow(corr_matrix, cmap='RdYlGn', vmin=-1, vmax=1)
plt.colorbar(im, ax=ax)

# Annotasi nilai korelasi
for i in range(len(TICKERS)):
    for j in range(len(TICKERS)):
        ax.text(j, i, f'{corr_matrix.iloc[i, j]:.2f}',
                ha='center', va='center', fontsize=12, fontweight='bold')

ax.set_xticks(range(len(TICKERS)))
ax.set_yticks(range(len(TICKERS)))
ax.set_xticklabels([t.replace('.JK', '') for t in TICKERS])
ax.set_yticklabels([t.replace('.JK', '') for t in TICKERS])
ax.set_title('🔗 Korelasi Harga Close Antar Saham', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.show()

"""---
# 4️⃣ Feature Engineering — Indikator Teknikal

Indikator teknikal adalah **sinyal matematis** yang dihitung dari data harga untuk membantu memprediksi pergerakan selanjutnya.

| Indikator | Fungsi |
|-----------|--------|
| **SMA 20/50** | Rata-rata harga 20/50 hari terakhir. Tren jangka pendek/panjang |
| **EMA 12** | Exponential Moving Average — lebih responsif terhadap perubahan harga terbaru |
| **RSI** | Relative Strength Index — mengukur overbought (>70) atau oversold (<30) |
| **MACD** | Moving Average Convergence Divergence — sinyal beli/jual dari persilangan garis |
| **Volatility** | Standar deviasi harga — seberapa 'liar' pergerakan harga |
| **Daily Return** | Persentase perubahan harga hari ini vs kemarin |
| **Bollinger Bands** | Batas atas-bawah harga normal berdasarkan volatilitas |
"""

# ============================================================
# CELL 1 — Feature Engineering yang diperkaya
# ============================================================
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

def engineer_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Buat fitur teknikal multi-dimensi dari OHLCV.
    df harus punya kolom: Open, High, Low, Close, Volume
    """
    d = df.copy()
    c = d['Close']
    v = d['Volume']
    h = d['High']
    l = d['Low']

    # --- Momentum multi-timeframe ---
    for n in [3, 5, 10, 20]:
        d[f'mom_{n}d']    = c.pct_change(n)
        d[f'return_{n}d'] = c / c.shift(n) - 1

    # Lag returns — penting buat model mendeteksi serial correlation
    for lag in [1, 2, 3, 5]:
        d[f'lag_ret_{lag}'] = c.pct_change(1).shift(lag)

    # --- RSI (14 dan 7 hari) ---
    def calc_rsi(series, period=14):
        delta = series.diff()
        gain  = delta.clip(lower=0).rolling(period).mean()
        loss  = (-delta.clip(upper=0)).rolling(period).mean()
        rs    = gain / (loss + 1e-9)
        return 100 - (100 / (1 + rs))

    d['rsi_14']    = calc_rsi(c, 14)
    d['rsi_7']     = calc_rsi(c, 7)
    d['rsi_div']   = d['rsi_14'] - d['rsi_7']          # divergence antar timeframe
    d['rsi_slope'] = d['rsi_14'].diff(3)                # arah RSI bergerak

    # --- MACD + histogram slope ---
    ema12          = c.ewm(span=12, adjust=False).mean()
    ema26          = c.ewm(span=26, adjust=False).mean()
    d['macd']      = ema12 - ema26
    d['macd_sig']  = d['macd'].ewm(span=9, adjust=False).mean()
    d['macd_hist'] = d['macd'] - d['macd_sig']
    d['macd_slope']= d['macd_hist'].diff(3)             # slope histogram = awal reversal

    # --- Bollinger Bands ---
    bb_mid         = c.rolling(20).mean()
    bb_std         = c.rolling(20).std()
    d['bb_pct']    = (c - (bb_mid - 2*bb_std)) / (4*bb_std + 1e-9)   # %B: 0=bawah, 1=atas
    d['bb_width']  = (4 * bb_std) / (bb_mid + 1e-9)                   # lebar band = volatility

    # --- ATR + volatility regime ---
    tr             = pd.concat([h - l, (h - c.shift()).abs(), (l - c.shift()).abs()], axis=1).max(axis=1)
    d['atr_14']    = tr.rolling(14).mean()
    d['atr_pct']   = d['atr_14'] / c                                  # ATR relatif terhadap harga
    d['vol_regime']= (d['atr_pct'] > d['atr_pct'].rolling(60).median()).astype(int)  # 1=high vol

    # --- Volume signals ---
    vol_ma20       = v.rolling(20).mean()
    vol_std20      = v.rolling(20).std()
    d['vol_zscore']= (v - vol_ma20) / (vol_std20 + 1e-9)              # anomaly volume
    d['vol_ratio'] = v / (vol_ma20 + 1e-9)                            # volume relatif

    # OBV (On-Balance Volume)
    obv            = (np.sign(c.diff()) * v).fillna(0).cumsum()
    d['obv_trend'] = obv.diff(5).apply(np.sign)                        # arah OBV 5 hari

    # Volume-price divergence: harga naik tapi volume turun = bearish
    d['vp_div']    = (c.pct_change(3) * d['vol_zscore'].shift(1))     # interaksi

    # --- Mean reversion signals ---
    for ma in [10, 20, 50]:
        d[f'dist_ma{ma}'] = (c / c.rolling(ma).mean()) - 1            # jarak dari MA

    # Z-score mean reversion (20 hari)
    d['zscore_20'] = (c - c.rolling(20).mean()) / (c.rolling(20).std() + 1e-9)

    # Distance dari 52-week high/low
    d['dist_52h']  = (c / h.rolling(252).max()) - 1                   # berapa % dari puncak
    d['dist_52l']  = (c / l.rolling(252).min()) - 1                   # berapa % dari dasar

    # --- Candlestick body ratio ---
    d['body_ratio']= (c - df['Open']).abs() / (tr + 1e-9)             # ukuran body vs total range
    d['upper_wick']= (h - pd.concat([c, df['Open']], axis=1).max(axis=1)) / (tr + 1e-9)
    d['lower_wick']= (pd.concat([c, df['Open']], axis=1).min(axis=1) - l) / (tr + 1e-9)

    return d

# Terapkan ke data kamu (sesuaikan dengan variabel data yang kamu punya)
# Contoh: df = engineer_features(raw_df)
print("✅ Fungsi engineer_features siap dipakai")
print(f"   Jumlah fitur yang dibuat: ~35 fitur teknikal")

# ============================================================
# Visualisasi Indikator Teknikal (Plotly Interactive)
# ============================================================

# Pastikan fitur sudah dibuat sebelum visualisasi
try:
    df_viz_full = engineer_features(df_raw)
    # Ambil 200 data terbaru untuk visualisasi yang lebih jelas
    df_viz = df_viz_full.tail(200)

    # Hitung SMA & BB secara manual untuk visualisasi karena fungsi engineer_features
    # yang baru menggunakan nama kolom yang berbeda
    df_viz['SMA_20'] = df_viz['Close'].rolling(20).mean()
    df_viz['SMA_50'] = df_viz['Close'].rolling(50).mean()
    std = df_viz['Close'].rolling(20).std()
    df_viz['BB_Upper'] = df_viz['SMA_20'] + (std * 2)
    df_viz['BB_Lower'] = df_viz['SMA_20'] - (std * 2)

    fig = make_subplots(
        rows=3, cols=1,
        shared_xaxes=True,
        subplot_titles=(
            f'📈 Harga & Moving Average — {PRIMARY_TICKER}',
            '📊 RSI (Relative Strength Index)',
            '📉 MACD'
        ),
        row_heights=[0.5, 0.25, 0.25],
        vertical_spacing=0.06
    )

    # --- Panel 1: Harga + SMA ---
    fig.add_trace(go.Scatter(x=df_viz.index, y=df_viz['Close'],
        name='Close', line=dict(color='#2196F3', width=1.5)), row=1, col=1)
    fig.add_trace(go.Scatter(x=df_viz.index, y=df_viz['SMA_20'],
        name='SMA 20', line=dict(color='#FF9800', width=1.2, dash='dash')), row=1, col=1)
    fig.add_trace(go.Scatter(x=df_viz.index, y=df_viz['SMA_50'],
        name='SMA 50', line=dict(color='#9C27B0', width=1.2, dash='dot')), row=1, col=1)
    fig.add_trace(go.Scatter(x=df_viz.index, y=df_viz['BB_Upper'],
        name='BB Upper', line=dict(color='#aaa', width=1, dash='dot'), showlegend=True), row=1, col=1)
    fig.add_trace(go.Scatter(x=df_viz.index, y=df_viz['BB_Lower'],
        name='BB Lower', line=dict(color='#aaa', width=1, dash='dot'),
        fill='tonexty', fillcolor='rgba(200,200,200,0.1)', showlegend=True), row=1, col=1)

    # --- Panel 2: RSI ---
    # Menggunakan rsi_14 dari engineer_features
    fig.add_trace(go.Scatter(x=df_viz.index, y=df_viz['rsi_14'],
        name='RSI', line=dict(color='#E91E63', width=1.5)), row=2, col=1)
    fig.add_hline(y=70, line_dash='dash', line_color='red', row=2, col=1, annotation_text='Overbought 70')
    fig.add_hline(y=30, line_dash='dash', line_color='green', row=2, col=1, annotation_text='Oversold 30')

    # --- Panel 3: MACD ---
    fig.add_trace(go.Scatter(x=df_viz.index, y=df_viz['macd'],
        name='MACD', line=dict(color='#009688', width=1.5)), row=3, col=1)
    fig.add_trace(go.Scatter(x=df_viz.index, y=df_viz['macd_sig'],
        name='Signal', line=dict(color='#FF5722', width=1.5, dash='dash')), row=3, col=1)
    colors_hist = ['#4CAF50' if v >= 0 else '#F44336' for v in df_viz['macd_hist']]
    fig.add_trace(go.Bar(x=df_viz.index, y=df_viz['macd_hist'],
        name='Histogram', marker_color=colors_hist, opacity=0.7), row=3, col=1)

    fig.update_layout(
        height=700,
        title_text=f'<b>📊 Analisis Teknikal — {PRIMARY_TICKER}</b>',
        hovermode='x unified',
        template='plotly_dark',
        legend=dict(orientation='h', y=1.02)
    )
    fig.show()
    print("✅ Grafik interaktif ditampilkan!")
except NameError as e:
    print(f"❌ Error: {e}. Pastikan cell 'sa8R2dHW0PM9' (engineer_features) sudah dijalankan.")

"""---
# 5️⃣ Preprocessing & Training

## 🤔 Kenapa XGBoost?

Kita menggunakan **XGBoost (Extreme Gradient Boosting)** karena:

1. **Robust terhadap noise** — data saham sangat noisy, XGBoost bisa menangani ini
2. **Handles non-linearity** — hubungan antara indikator teknikal dan harga tidak selalu linear
3. **Feature importance built-in** — kita bisa tahu indikator mana yang paling berpengaruh
4. **Fast & scalable** — efisien untuk dataset ratusan ribu baris
5. **Kaggle favorite** — terbukti di banyak kompetisi prediksi finansial

> Random Forest juga disertakan sebagai pembanding (baseline).
"""

# ============================================================
# CELL 2 — Target smarter + Walk-Forward Split
# ============================================================

def create_target(df: pd.DataFrame, forward_days: int = 3, min_return: float = 0.005) -> pd.Series:
    """
    Target yang lebih bersih:
    - 1 = return positif signifikan (> min_return) dalam forward_days ke depan
    - 0 = sebaliknya
    Menghindari noise microstructure dari prediksi 1-hari.
    """
    forward_ret = df['Close'].pct_change(forward_days).shift(-forward_days)
    return (forward_ret > min_return).astype(int)


def walk_forward_split(df: pd.DataFrame, n_splits: int = 4, test_ratio: float = 0.15):
    """
    Buat split kronologis — tidak ada data leak.
    Setiap split: train pakai semua data sebelum test window.
    """
    n = len(df)
    test_size  = int(n * test_ratio)
    total_test = test_size * n_splits

    splits = []
    for i in range(n_splits):
        test_end   = n - i * test_size
        test_start = test_end - test_size
        # Minimal train = 252 hari (1 tahun)
        if test_start < 252:
            break
        splits.append((
            df.index[:test_start],
            df.index[test_start:test_end]
        ))

    return list(reversed(splits))   # urutan kronologis


# ============================================================
# Siapkan fitur dan target — SESUAIKAN nama variabel kamu
# ============================================================

# Asumsi: raw_df adalah DataFrame dengan OHLCV yang sudah di-download
# raw_df = yf.download(PRIMARY_TICKER, start=START_DATE, end=END_DATE)
# raw_df.columns = raw_df.columns.droplevel(1) jika multi-level

df_feat = engineer_features(df_raw)
df_feat['target'] = create_target(df_feat, forward_days=3, min_return=0.005)

# Hapus baris dengan NaN (dari rolling window) dan forward-looking NaN
df_feat.dropna(inplace=True)

# Pilih kolom fitur (semua kecuali OHLCV raw dan target)
EXCLUDE   = ['Open', 'High', 'Low', 'Close', 'Volume', 'Adj Close', 'target']
FEATURE_COLS = [c for c in df_feat.columns if c not in EXCLUDE]

print(f"📊 Total data bersih : {len(df_feat)} baris")
print(f"📌 Jumlah fitur      : {len(FEATURE_COLS)}")
print(f"🎯 Distribusi target : Naik={df_feat['target'].mean():.1%} | Turun/Flat={(1-df_feat['target'].mean()):.1%}")
print(f"\nFitur yang digunakan:")
for i, col in enumerate(FEATURE_COLS, 1):
    print(f"  {i:2d}. {col}")

# ============================================================
# Train-Test Split (time-series aware)
# ============================================================
# PENTING: Untuk data time-series, kita TIDAK boleh shuffle!
# Data train = masa lalu, data test = masa depan

# Siapkan array X dan y dari df_feat
X = df_feat[FEATURE_COLS].values
y = df_feat['target'].values

SPLIT_RATIO = 0.8  # 80% train, 20% test
split_idx   = int(len(X) * SPLIT_RATIO)

X_train, X_test = X[:split_idx], X[split_idx:]
y_train, y_test = y[:split_idx], y[split_idx:]

# Tanggal split
split_date = df_feat.index[split_idx].date()

print("📂 Train-Test Split (Time-Series):")
print(f"   Training : {X_train.shape[0]:,} sampel ({df_feat.index[0].date()} → {split_date})")
print(f"   Testing  : {X_test.shape[0]:,} sampel ({split_date} → {df_feat.index[-1].date()})")
print(f"   Ratio    : {SPLIT_RATIO*100:.0f}% / {(1-SPLIT_RATIO)*100:.0f}%")

# ============================================================
# Scaling (StandardScaler)
# ============================================================
# XGBoost sebenarnya tidak membutuhkan scaling,
# tapi kita tetap lakukan agar konsisten dan mudah digunakan
# untuk model lain yang mungkin membutuhkannya.
# PENTING: fit scaler HANYA pada data train!

from sklearn.impute import SimpleImputer
import numpy as np

# First, ensure there are no infinite values. StandardScaler cannot handle np.inf.
# It's possible some feature calculations (e.g., division by zero in ratios)
# resulted in infinite values. We will replace them with NaN and then impute.
X_train_cleaned = np.nan_to_num(X_train, nan=np.nan, posinf=np.nan, neginf=np.nan)
X_test_cleaned  = np.nan_to_num(X_test, nan=np.nan, posinf=np.nan, neginf=np.nan)

# Impute NaN values. Using mean strategy from the training set.
imputer = SimpleImputer(strategy='mean')
X_train_imputed = imputer.fit_transform(X_train_cleaned)
X_test_imputed  = imputer.transform(X_test_cleaned)

# Now apply StandardScaler to the cleaned and imputed data
scaler  = StandardScaler()
X_train = scaler.fit_transform(X_train_imputed)  # fit + transform
X_test  = scaler.transform(X_test_imputed)       # transform saja (pakai parameter dari train)

print("✅ Scaling selesai!")
print(f"   Mean fitur pertama (train): {scaler.mean_[0]:.4f}")
print(f"   Std fitur pertama  (train): {scaler.scale_[0]:.4f}")

# ============================================================
# CELL 3 — Training XGBoost + Optuna dengan Walk-Forward CV
# ============================================================
!pip install optuna xgboost --quiet

import optuna
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, roc_auc_score, classification_report
from sklearn.preprocessing import RobustScaler
import numpy as np

optuna.logging.set_verbosity(optuna.logging.WARNING)

X = df_feat[FEATURE_COLS].values
y = df_feat['target'].values
idx = df_feat.index

splits = walk_forward_split(df_feat, n_splits=4, test_ratio=0.15)
print(f"🔀 Walk-forward splits: {len(splits)} fold")

# -------------------------------------------------------
# Optuna: objective pakai walk-forward bukan random CV
# -------------------------------------------------------
def objective(trial):
    params = {
        'n_estimators':     trial.suggest_int('n_estimators', 200, 800),
        'max_depth':        trial.suggest_int('max_depth', 3, 7),
        'learning_rate':    trial.suggest_float('learning_rate', 0.005, 0.15, log=True),
        'subsample':        trial.suggest_float('subsample', 0.6, 0.9),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 0.9),
        'min_child_weight': trial.suggest_int('min_child_weight', 3, 15),
        'gamma':            trial.suggest_float('gamma', 0.1, 2.0),
        'reg_alpha':        trial.suggest_float('reg_alpha', 0.0, 1.0),   # L1 regularization
        'reg_lambda':       trial.suggest_float('reg_lambda', 0.5, 5.0),  # L2 regularization
        'eval_metric':      'logloss',
        'early_stopping_rounds': 30, # Dipindahkan ke sini (XGBoost 2.0+)
        'random_state':     42,
        'n_jobs':           -1,
    }

    fold_scores = []
    for train_idx, test_idx in splits:
        loc_train = df_feat.index.isin(train_idx)
        loc_test  = df_feat.index.isin(test_idx)

        X_tr, y_tr = X[loc_train], y[loc_train]
        X_te, y_te = X[loc_test],  y[loc_test]

        # Imbalance handling per fold
        neg, pos  = np.sum(y_tr == 0), np.sum(y_tr == 1)
        spw       = neg / (pos + 1e-9) if abs(neg/pos - 1) > 0.1 else 1.0

        # Scale fitur
        scaler  = RobustScaler()
        X_tr_sc = scaler.fit_transform(X_tr)
        X_te_sc = scaler.transform(X_te)

        m = XGBClassifier(**params, scale_pos_weight=spw)
        m.fit(X_tr_sc, y_tr,
              eval_set=[(X_te_sc, y_te)],
              verbose=False)

        pred  = m.predict(X_te_sc)
        score = accuracy_score(y_te, pred)
        fold_scores.append(score)

    return np.mean(fold_scores)


# -------------------------------------------------------
# Jalankan Optuna
# -------------------------------------------------------
print("🔍 Menjalankan Optuna hyperparameter search (75 trials)...")
study = optuna.create_study(
    direction='maximize',
    sampler=optuna.samplers.TPESampler(seed=42)
)
study.optimize(objective, n_trials=75, show_progress_bar=True)

print(f"\n🏆 Best walk-forward accuracy : {study.best_value:.4f}")
print(f"   Best params: {study.best_params}")


# -------------------------------------------------------
# Training final model + evaluasi per fold
# -------------------------------------------------------
print("\n📈 Evaluasi per fold (walk-forward):")
print("-" * 55)

best_params = study.best_params
fold_results = []

for i, (train_idx, test_idx) in enumerate(splits, 1):
    loc_train = df_feat.index.isin(train_idx)
    loc_test  = df_feat.index.isin(test_idx)

    X_tr, y_tr = X[loc_train], y[loc_train]
    X_te, y_te = X[loc_test],  y[loc_test]

    neg, pos  = np.sum(y_tr == 0), np.sum(y_tr == 1)
    spw       = neg / (pos + 1e-9) if abs(neg/pos - 1) > 0.1 else 1.0

    scaler    = RobustScaler()
    X_tr_sc   = scaler.fit_transform(X_tr)
    X_te_sc   = scaler.transform(X_te)

    model = XGBClassifier(**best_params,
        eval_metric='logloss', early_stopping_rounds=30,
        random_state=42, n_jobs=-1, scale_pos_weight=spw)

    model.fit(X_tr_sc, y_tr,
              eval_set=[(X_te_sc, y_te)],
              verbose=False)

    proba  = model.predict_proba(X_te_sc)[:, 1]
    pred   = (proba > 0.5).astype(int)

    acc    = accuracy_score(y_te, pred)
    auc    = roc_auc_score(y_te, proba)

    # Confident predictions only (threshold 60%)
    mask_conf = (proba >= 0.60) | (proba <= 0.40)
    if mask_conf.sum() > 0:
        acc_conf = accuracy_score(y_te[mask_conf], pred[mask_conf])
        coverage = mask_conf.mean()
    else:
        acc_conf, coverage = acc, 1.0

    fold_results.append({'fold': i, 'acc': acc, 'auc': auc,
                         'acc_conf': acc_conf, 'coverage': coverage,
                         'model': model, 'scaler': scaler})

    print(f"  Fold {i}: acc={acc:.4f} | AUC={auc:.4f} | "
          f"acc@60%conf={acc_conf:.4f} (coverage={coverage:.1%})")

# Simpan model fold terbaik (berdasarkan AUC)
best_fold   = max(fold_results, key=lambda x: x['auc'])
xgb_model   = best_fold['model']
final_scaler= best_fold['scaler']

print(f"\n✅ Model terbaik: Fold {best_fold['fold']} "
      f"(AUC={best_fold['auc']:.4f})")
print(f"\n{'='*55}")
print("📋 Classification report (fold terbaik):")
loc_test_best = df_feat.index.isin(splits[best_fold['fold']-1][1])
X_te_final    = final_scaler.transform(X[loc_test_best])
y_te_final    = y[loc_test_best]
print(classification_report(y_te_final, xgb_model.predict(X_te_final),
      target_names=['Turun/Flat', 'Naik']))

import joblib
import os

# Bundle model dan metadata pendukung agar mudah digunakan saat inference
model_bundle = {
    'model': xgb_model,
    'scaler': final_scaler,
    'feature_cols': FEATURE_COLS,
    'ticker': PRIMARY_TICKER,
    'train_date': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
    'best_params': study.best_params,
    'accuracy_val': best_fold['acc']
}

# Nama file
SAVE_PATH = 'best_xgb_stock_model.pkl'

# Simpan model
joblib.dump(model_bundle, SAVE_PATH)

file_size = os.path.getsize(SAVE_PATH) / 1024  # KB
print(f"✅ Model berhasil disimpan!")
print(f"📂 File: {SAVE_PATH}")
print(f"📦 Ukuran: {file_size:.1f} KB")
print(f"🎯 Accuracy (Best Fold): {best_fold['acc']*100:.2f}%")
print(f"🚀 Ticker Utama: {PRIMARY_TICKER}")

"""---
# 6️⃣ Evaluasi Model

Kita evaluasi model menggunakan:
- **Accuracy** — persentase prediksi yang benar
- **Confusion Matrix** — detail kesalahan prediksi
- **Classification Report** — precision, recall, F1-score per kelas

> 💡 Dalam trading, **precision** lebih penting dari accuracy!
> Lebih baik miss beberapa peluang daripada salah masuk posisi.
"""

# ============================================================
# Confusion Matrix (visual)
# ============================================================

fig, axes = plt.subplots(1, 2, figsize=(12, 5))

for ax, model, pred, name, color in zip(
    axes,
    [xgb_model, rf_model],
    [xgb_pred, rf_pred],
    ['XGBoost', 'Random Forest'],
    ['Blues', 'Greens']
):
    cm = confusion_matrix(y_test, pred)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Turun', 'Naik'])
    disp.plot(ax=ax, cmap=color, colorbar=False)
    ax.set_title(f'🔲 Confusion Matrix — {name}\nAccuracy: {accuracy_score(y_test, pred)*100:.2f}%',
                 fontsize=13, fontweight='bold')

plt.tight_layout()
plt.savefig('confusion_matrix.png', dpi=150, bbox_inches='tight')
plt.show()
print("\n📌 Cara Membaca Confusion Matrix:")
print("   True Negative  (kiri atas)  : Prediksi Turun, Aktual Turun ✅")
print("   False Positive (kanan atas) : Prediksi Naik,  Aktual Turun ❌")
print("   False Negative (kiri bawah) : Prediksi Turun, Aktual Naik  ❌")
print("   True Positive  (kanan bawah): Prediksi Naik,  Aktual Naik  ✅")

# ============================================================
# Perbandingan Akurasi Model
# ============================================================

models_compared = {'XGBoost': xgb_acc, 'Random Forest': rf_acc}

fig, ax = plt.subplots(figsize=(7, 4))
bars = ax.bar(
    models_compared.keys(),
    [v * 100 for v in models_compared.values()],
    color=['#2196F3', '#4CAF50'], width=0.4, edgecolor='white', linewidth=1.5
)

for bar, (name, acc) in zip(bars, models_compared.items()):
    ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.3,
            f'{acc*100:.2f}%', ha='center', va='bottom', fontsize=13, fontweight='bold')

ax.set_ylim(0, 100)
ax.set_ylabel('Accuracy (%)', fontsize=12)
ax.set_title('🏆 Perbandingan Akurasi Model', fontsize=14, fontweight='bold')
ax.axhline(y=50, color='red', linestyle='--', linewidth=1, label='Random Baseline (50%)')
ax.legend()
ax.grid(True, axis='y', alpha=0.3)
plt.tight_layout()
plt.savefig('model_comparison.png', dpi=150, bbox_inches='tight')
plt.show()

best_model_name = max(models_compared, key=models_compared.get)
print(f"\n🏆 Model terbaik: {best_model_name} ({models_compared[best_model_name]*100:.2f}%)")

"""---
# 7️⃣ Visualisasi Lanjutan
"""

# ============================================================
# Feature Importance
# ============================================================
# Indikator mana yang paling berpengaruh terhadap prediksi?

importances = pd.Series(
    xgb_model.feature_importances_,
    index=FEATURE_COLS
).sort_values(ascending=True)

fig, ax = plt.subplots(figsize=(9, max(6, len(FEATURE_COLS) * 0.35)))
colors_fi = ['#F44336' if v >= importances.quantile(0.75)
             else '#FF9800' if v >= importances.quantile(0.5)
             else '#90CAF9' for v in importances]

bars = ax.barh(importances.index, importances.values, color=colors_fi, edgecolor='white')

for bar, val in zip(bars, importances.values):
    ax.text(val + 0.001, bar.get_y() + bar.get_height()/2,
            f'{val:.3f}', va='center', fontsize=8)

ax.set_xlabel('Feature Importance Score', fontsize=11)
ax.set_title('🔍 Feature Importance — XGBoost\n(Indikator paling berpengaruh)', fontsize=13, fontweight='bold')
ax.grid(True, axis='x', alpha=0.3)
plt.tight_layout()
plt.savefig('feature_importance.png', dpi=150, bbox_inches='tight')
plt.show()

print("\n🏅 Top 5 Fitur Paling Penting:")
for i, (feat, score) in enumerate(importances.sort_values(ascending=False).head(5).items(), 1):
    print(f"   {i}. {feat}: {score:.4f}")

# ============================================================
# Prediksi vs Aktual — visualisasi pada test set
# ============================================================

# Ambil data test
df_test_viz = df_feat.iloc[split_idx:].copy()
df_test_viz['Pred_XGB']   = xgb_pred
df_test_viz['Proba_XGB']  = xgb_proba
df_test_viz['Pred_RF']    = rf_pred
df_test_viz['Correct_XGB'] = (df_test_viz['Pred_XGB'] == df_test_viz['Label']).astype(int)

# Tampilkan 60 hari terakhir
n_show = 60
df_show = df_test_viz.tail(n_show)

fig, axes = plt.subplots(2, 1, figsize=(14, 8), sharex=True)

# Panel atas: harga + prediksi
ax1 = axes[0]
ax1.plot(df_show.index, df_show['Close'], color='#2196F3', linewidth=1.5, label='Harga Close', zorder=3)

# Tandai titik dengan warna berdasarkan prediksi vs aktual
for _, row in df_show.iterrows():
    color = '#4CAF50' if row['Correct_XGB'] == 1 else '#F44336'
    marker = '^' if row['Pred_XGB'] == 1 else 'v'
    ax1.scatter(row.name, row['Close'], color=color, marker=marker, s=40, zorder=4, alpha=0.8)

# Legend manual
from matplotlib.lines import Line2D
legend_elements = [
    Line2D([0], [0], marker='^', color='w', markerfacecolor='#4CAF50', markersize=10, label='Prediksi Naik (Benar)'),
    Line2D([0], [0], marker='^', color='w', markerfacecolor='#F44336', markersize=10, label='Prediksi Naik (Salah)'),
    Line2D([0], [0], marker='v', color='w', markerfacecolor='#4CAF50', markersize=10, label='Prediksi Turun (Benar)'),
    Line2D([0], [0], marker='v', color='w', markerfacecolor='#F44336', markersize=10, label='Prediksi Turun (Salah)'),
]
ax1.legend(handles=legend_elements, loc='upper left', fontsize=8)
ax1.set_title(f'📍 Prediksi vs Aktual — {PRIMARY_TICKER} (60 hari terakhir)', fontsize=13, fontweight='bold')
ax1.set_ylabel('Harga (IDR)')
ax1.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f'Rp {x:,.0f}'))
ax1.grid(True, alpha=0.3)

# Panel bawah: confidence score
ax2 = axes[1]
ax2.bar(df_show.index, df_show['Proba_XGB'],
        color=['#4CAF50' if p >= 0.5 else '#F44336' for p in df_show['Proba_XGB']],
        alpha=0.8, width=1)
ax2.axhline(y=0.5, color='black', linestyle='--', linewidth=1)
ax2.set_ylabel('Confidence Score')
ax2.set_title('📊 Confidence Score (Probabilitas Naik)', fontsize=11)
ax2.set_ylim(0, 1)
ax2.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('prediksi_vs_aktual.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ Plot prediksi vs aktual disimpan!")

# ============================================================
# Distribusi Confidence Score
# ============================================================

fig, axes = plt.subplots(1, 2, figsize=(12, 4))

# Distribusi probabilitas
axes[0].hist(df_test_viz[df_test_viz['Label']==1]['Proba_XGB'],
             bins=30, alpha=0.7, color='#4CAF50', label='Aktual Naik')
axes[0].hist(df_test_viz[df_test_viz['Label']==0]['Proba_XGB'],
             bins=30, alpha=0.7, color='#F44336', label='Aktual Turun')
axes[0].set_xlabel('Confidence Score (Prob. Naik)')
axes[0].set_ylabel('Frekuensi')
axes[0].set_title('Distribusi Confidence per Kelas Aktual', fontweight='bold')
axes[0].axvline(x=0.5, color='black', linestyle='--')
axes[0].legend()
axes[0].grid(True, alpha=0.3)

# Accuracy per confidence bucket
df_test_viz['Conf_Bucket'] = pd.cut(df_test_viz['Proba_XGB'],
                                     bins=[0, 0.4, 0.5, 0.6, 0.7, 1.0],
                                     labels=['<40%', '40-50%', '50-60%', '60-70%', '>70%'])
acc_per_bucket = df_test_viz.groupby('Conf_Bucket', observed=True).apply(
    lambda x: accuracy_score(x['Label'], x['Pred_XGB'])
) * 100

axes[1].bar(acc_per_bucket.index, acc_per_bucket.values, color='#2196F3', edgecolor='white')
axes[1].axhline(y=50, color='red', linestyle='--', linewidth=1, label='Baseline 50%')
for i, (bucket, acc) in enumerate(acc_per_bucket.items()):
    axes[1].text(i, acc + 1, f'{acc:.1f}%', ha='center', fontsize=10, fontweight='bold')
axes[1].set_xlabel('Confidence Score Bucket')
axes[1].set_ylabel('Accuracy (%)')
axes[1].set_title('Accuracy per Confidence Level', fontweight='bold')
axes[1].set_ylim(0, 100)
axes[1].legend()
axes[1].grid(True, alpha=0.3, axis='y')

plt.suptitle('🎯 Analisis Confidence Score — XGBoost', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

"""---
# 8️⃣ Save Model
"""

# ============================================================
# Simpan model, scaler, dan metadata ke file .pkl
# ============================================================

# Bundle semua yang dibutuhkan untuk inference
model_bundle = {
    'model'        : xgb_model,           # model XGBoost terlatih
    'scaler'       : scaler,              # StandardScaler (fit pada train)
    'feature_cols' : FEATURE_COLS,        # nama fitur (urutan penting!)
    'ticker'       : PRIMARY_TICKER,      # ticker yang dilatih
    'train_date'   : str(datetime.now()), # waktu training
    'accuracy'     : xgb_acc,            # akurasi di test set
    'split_date'   : str(split_date),    # batas train/test
}

# Simpan single-stock model
MODEL_PATH = 'model_saham.pkl'
joblib.dump(model_bundle, MODEL_PATH)
# → upload ke Hugging Face Spaces / Supabase Storage
# → FastAPI endpoint /predict?ticker=BBCA baca dari sini

file_size = os.path.getsize(MODEL_PATH) / 1024  # KB
print(f"✅ Model berhasil disimpan!")
print(f"   📁 Path      : {MODEL_PATH}")
print(f"   📦 Ukuran    : {file_size:.1f} KB")
print(f"   🎯 Accuracy  : {xgb_acc*100:.2f}%")
print(f"   🏷️ Ticker    : {PRIMARY_TICKER}")
print(f"   🔧 Fitur     : {len(FEATURE_COLS)} indikator")
print()

# Verifikasi: load ulang dan cek
loaded = joblib.load(MODEL_PATH)
verify_pred = loaded['model'].predict(loaded['scaler'].transform(X_test[:5]))
print(f"🔍 Verifikasi load model: prediksi 5 sampel pertama = {verify_pred}")
print("✅ Model berjalan normal setelah di-load!")

"""---
# 9️⃣ 🔴 Realtime Prediction Simulation

Simulasi bagaimana model digunakan dalam kondisi **nyata / production**.

### 🔄 Flow:
```
1. Fetch data terbaru dari yfinance
       ↓
2. Generate semua indikator teknikal
       ↓
3. Load model .pkl
       ↓
4. Prediksi arah saham besok
       ↓
5. Tampilkan confidence score & rekomendasi
       ↓
6. Hitung target take profit & stop loss
```
"""

import joblib
from datetime import datetime, timedelta

def predict_stock(ticker: str, model_path: str = 'model_saham.pkl') -> dict:
    """
    Fungsi prediksi real-time untuk satu ticker saham.

    Parameters:
        ticker     : kode saham (contoh: 'BBCA.JK')
        model_path : path file model .pkl

    Returns:
        dict berisi prediksi, confidence, rekomendasi, TP, SL
    """
    # --- 1. Load model bundle ---
    bundle      = joblib.load(model_path)
    model       = bundle['model']
    scaler      = bundle['scaler']
    feat_cols   = bundle['feature_cols']

    # --- 2. Fetch data terbaru (ambil 200 hari untuk rolling indicator) ---
    end_dt   = datetime.today().strftime('%Y-%m-%d')
    start_dt = (datetime.today() - timedelta(days=300)).strftime('%Y-%m-%d')
    raw      = fetch_stock_data(ticker, start_dt, end_dt)

    if len(raw) < 60:
        raise ValueError(f"Data tidak cukup untuk {ticker}: hanya {len(raw)} baris.")

    # --- 3. Generate fitur ---
    df_proc = add_features(raw)

    # Ambil baris TERAKHIR sebagai input prediksi
    latest      = df_proc.iloc[-1]
    X_latest    = latest[feat_cols].values.reshape(1, -1)
    X_scaled    = scaler.transform(X_latest)

    # --- 4. Prediksi ---
    pred        = model.predict(X_scaled)[0]
    proba       = model.predict_proba(X_scaled)[0]  # [prob_turun, prob_naik]
    confidence  = proba[pred] * 100

    # --- 5. Informasi harga terkini ---
    current_price = float(latest['Close'])
    rsi_val       = float(latest['RSI'])
    macd_diff_val = float(latest['MACD_Diff'])
    latest_date   = raw.index[-1].strftime('%Y-%m-%d') # Get the latest date

    # --- 6. Rekomendasi ---
    if pred == 1:
        direction   = 'NAIK 📈'
        signal      = 'BULLISH 🟢'
        take_profit = current_price * 1.03   # target +3%
        stop_loss   = current_price * 0.98   # batas rugi -2%
        action      = 'BUY'
    else:
        direction   = 'TURUN 📉'
        signal      = 'BEARISH 🔴'
        take_profit = current_price * 0.97   # target short -3%
        stop_loss   = current_price * 1.02   # batas rugi short +2%
        action      = 'WAIT / SELL'

    # Kekuatan sinyal berdasarkan confidence
    if confidence >= 70:
        strength = 'KUAT 💪'
    elif confidence >= 60:
        strength = 'SEDANG 👍'
    else:
        strength = 'LEMAH ⚠️'

    return {
    "ticker": ticker,
    "tanggal": latest_date,      # Add the latest date here
    "prediksi": direction,
    "signal": signal,           # "BULLISH 🟢" / "BEARISH 🔴"
    "action": action,           # "BUY" / "WAIT / SELL"
    "confidence": round(confidence, 1),
    "prob_naik": round(proba[1] * 100, 1),
    "prob_turun": round(proba[0] * 100, 1),
    "harga_sekarang": current_price,
    "take_profit": round(take_profit, 0),
    "stop_loss": round(stop_loss, 0),
    "rsi": round(rsi_val, 2),
    "macd_diff": round(macd_diff_val, 4),
    "change_pct": round(df_proc['Daily_Return'].iloc[-1], 2),  # untuk +1.25% di card
    "strength": strength
}


print("✅ Fungsi predict_stock() siap digunakan!")

# ============================================================
# Jalankan prediksi untuk semua ticker
# ============================================================

print("🔴 REALTIME PREDICTION SIMULATION")
print("=" * 60)
print(f"⏰ Waktu Analisis: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
print()

results = []
for ticker in TICKERS:
    try:
        result = predict_stock(ticker)
        results.append(result)
    except Exception as e:
        print(f"⚠️ Gagal prediksi {ticker}: {e}")

print()

# ============================================================
# Tampilkan hasil prediksi dalam format laporan
# ============================================================

for r in results:
    border = '=' * 55
    print(border)
    print(f"  🏦 {r['ticker']}  —  {r['tanggal']}")
    print(border)
    print(f"  💰 Harga Sekarang : Rp {r['harga_sekarang']:>12,.0f}")
    print(f"  🎯 Prediksi       : {r['prediksi']}")
    print(f"  📡 Signal         : {r['signal']}")
    print(f"  🏃 Action         : {r['action']}")
    print(f"  ─────────────────────────────────────────────")
    print(f"  📊 Confidence     : {r['confidence']:.1f}% ({r['strength']})")
    print(f"  📈 Prob. Naik     : {r['prob_naik']:.1f}%")
    print(f"  📉 Prob. Turun    : {r['prob_turun']:.1f}%")
    print(f"  ─────────────────────────────────────────────")
    print(f"  🎯 Take Profit    : Rp {r['take_profit']:>12,.0f}  (+3%)")
    print(f"  🛑 Stop Loss      : Rp {r['stop_loss']:>12,.0f}  (-2%)")
    print(f"  ─────────────────────────────────────────────")
    print(f"  📐 RSI            : {r['rsi']:.2f}  {'(Overbought ⚠️)' if r['rsi']>70 else '(Oversold ⚠️)' if r['rsi']<30 else '(Normal ✅)'}")
    print(f"  📉 MACD Diff      : {r['macd_diff']:.4f}  {'(Bullish ↑)' if r['macd_diff']>0 else '(Bearish ↓)'}")
    print(border)
    print()

# ============================================================
# Dashboard ringkasan semua saham
# ============================================================

fig, axes = plt.subplots(1, len(results), figsize=(5 * len(results), 5))

if len(results) == 1:
    axes = [axes]

for ax, r in zip(axes, results):
    # Pie chart: probabilitas naik vs turun
    sizes  = [r['prob_naik'], r['prob_turun']]
    labels = [f"Naik\n{r['prob_naik']:.1f}%", f"Turun\n{r['prob_turun']:.1f}%"]
    colors_pie = ['#4CAF50', '#F44336']
    explode    = (0.05, 0) if r['prob_naik'] > r['prob_turun'] else (0, 0.05)

    wedges, texts, autotexts = ax.pie(
        sizes, labels=labels, colors=colors_pie,
        explode=explode, autopct='', startangle=90,
        wedgeprops={'edgecolor': 'white', 'linewidth': 2}
    )

    # Teks di tengah
    signal_color = '#4CAF50' if r['prob_naik'] > r['prob_turun'] else '#F44336'
    ax.text(0, 0.15, r['action'], ha='center', va='center',
            fontsize=14, fontweight='bold', color=signal_color)
    ax.text(0, -0.15, f"{r['confidence']:.0f}%", ha='center', va='center',
            fontsize=12, color='gray')

    title_color = '#4CAF50' if 'BULLISH' in r['signal'] else '#F44336'
    ax.set_title(f"{r['ticker'].replace('.JK','')}\n{r['signal']}\nRp {r['harga_sekarang']:,.0f}",
                 fontsize=11, fontweight='bold', color=title_color)

plt.suptitle('🔴 InvestAI — Realtime Prediction Dashboard', fontsize=15, fontweight='bold')
plt.tight_layout()
plt.savefig('realtime_dashboard.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ Dashboard disimpan: realtime_dashboard.png")

"""---
# 🔟 Multi-Stock Training (Bonus)

Latih model dengan **gabungan data semua ticker** untuk meningkatkan generalisasi.
"""

# ============================================================
# Multi-Stock Training: gabungkan data semua saham
# ============================================================

print("🔄 Multi-Stock Training...")

# Gabungkan semua data yang sudah di-feature engineering
dfs_all = []
for ticker in TICKERS:
    df_t = add_features(all_data[ticker].copy())
    df_t['Ticker'] = ticker  # tambahkan kolom identitas
    dfs_all.append(df_t)

df_multi = pd.concat(dfs_all, axis=0).sort_index()

print(f"✅ Dataset gabungan: {df_multi.shape[0]:,} baris dari {len(TICKERS)} saham")

# Pisahkan fitur & target
X_multi = df_multi[FEATURE_COLS].values
y_multi = df_multi['Label'].values

# Split (time-aware: kita sort by index terlebih dahulu)
split_multi = int(len(X_multi) * 0.8)
Xm_train, Xm_test = X_multi[:split_multi], X_multi[split_multi:]
ym_train, ym_test = y_multi[:split_multi], y_multi[split_multi:]

# --- Scaling (StandardScaler) for Multi-Stock Data ---
# First, ensure there are no infinite values. StandardScaler cannot handle np.inf.
Xm_train_cleaned = np.nan_to_num(Xm_train, nan=np.nan, posinf=np.nan, neginf=np.nan)
Xm_test_cleaned  = np.nan_to_num(Xm_test, nan=np.nan, posinf=np.nan, neginf=np.nan)

# Impute NaN values. Using mean strategy from the training set.
imputer_multi = SimpleImputer(strategy='mean')
Xm_train_imputed = imputer_multi.fit_transform(Xm_train_cleaned)
Xm_test_imputed  = imputer_multi.transform(Xm_test_cleaned)

scaler_multi = StandardScaler()
Xm_train_scaled = scaler_multi.fit_transform(Xm_train_imputed)
Xm_test_scaled  = scaler_multi.transform(Xm_test_imputed)

# Training XGBoost
xgb_multi = XGBClassifier(
    n_estimators=300, max_depth=5, learning_rate=0.05,
    subsample=0.8, colsample_bytree=0.8,
    use_label_encoder=False, eval_metric='logloss',
    random_state=42, n_jobs=-1
)
xgb_multi.fit(Xm_train_scaled, ym_train, eval_set=[(Xm_test_scaled, ym_test)], verbose=False)

multi_xgb_acc = accuracy_score(ym_test, xgb_multi.predict(Xm_test_scaled))
print(f"\n🏆 Multi-Stock XGBoost Model Accuracy: {multi_xgb_acc*100:.2f}%")
print(f"   Bandingkan dengan single-stock XGBoost: {xgb_acc*100:.2f}%")

# Simpan multi-stock XGBoost model
multi_xgb_bundle = {
    'model'        : xgb_multi,
    'scaler'       : scaler_multi,
    'feature_cols' : FEATURE_COLS,
    'tickers'      : TICKERS,
    'accuracy'     : multi_xgb_acc,
    'train_date'   : str(datetime.now())
}
joblib.dump(multi_xgb_bundle, 'model_saham_multi_xgb.pkl')
print("✅ Model multi-stock XGBoost disimpan: model_saham_multi_xgb.pkl")

# --- Training Random Forest for Multi-Stock ---
print("\n🌲 Training multi-stock Random Forest...")
rf_multi = RandomForestClassifier(
    n_estimators=200, max_depth=7, random_state=42, n_jobs=-1
)
rf_multi.fit(Xm_train_scaled, ym_train)

multi_rf_acc = accuracy_score(ym_test, rf_multi.predict(Xm_test_scaled))
print(f"🏆 Multi-Stock Random Forest Model Accuracy: {multi_rf_acc*100:.2f}%")
print(f"   Bandingkan dengan single-stock Random Forest: {rf_acc*100:.2f}%")

# Simpan multi-stock Random Forest model
multi_rf_bundle = {
    'model'        : rf_multi,
    'scaler'       : scaler_multi, # Use the same scaler fitted on multi-stock data
    'feature_cols' : FEATURE_COLS,
    'tickers'      : TICKERS,
    'accuracy'     : multi_rf_acc,
    'train_date'   : str(datetime.now())
}
joblib.dump(multi_rf_bundle, 'model_saham_multi_rf.pkl')
print("✅ Model multi-stock Random Forest disimpan: model_saham_multi_rf.pkl")

"""---
# 1️⃣1️⃣ Ringkasan & Kesimpulan

## 📊 Ringkasan Hasil
"""

# ============================================================
# Ringkasan akhir project
# ============================================================

print()
print("╔══════════════════════════════════════════════════════╗")
print("║          📈 InvestAI — Project Summary               ║")
print("╠══════════════════════════════════════════════════════╣")
print(f"║  🏦 Ticker Utama      : {PRIMARY_TICKER:<28}║")
print(f"║  📅 Periode Data      : {START_DATE} → {END_DATE:<10}║")
print(f"║  📊 Total Data (rows) : {len(df_feat):<28}║")
print(f"║  🔧 Jumlah Fitur      : {len(FEATURE_COLS):<28}║")
print("╠══════════════════════════════════════════════════════╣")
print(f"║  🤖 XGBoost Accuracy  : {xgb_acc*100:.2f}%{' '*22}║")
print(f"║  🌲 Random Forest Acc : {rf_acc*100:.2f}%{' '*22}║")
print(f"║  🏆 Multi-Stock XGBoost Acc: {multi_xgb_acc*100:.2f}%{' '*14}║")
print(f"║  🏆 Multi-Stock RF Acc: {multi_rf_acc*100:.2f}%{' '*17}║")
print("╠══════════════════════════════════════════════════════╣")
print("║  📁 File yang dihasilkan:                            ║")
print("║     ✅ model_saham.pkl           (single-stock)      ║")
print("║     ✅ model_saham_multi_xgb.pkl (multi-stock XGB)   ║")
print("║     ✅ model_saham_multi_rf.pkl  (multi-stock RF)    ║")
print("║     ✅ plot_harga_historis.png                       ║")
print("║     ✅ confusion_matrix.png                          ║")
print("║     ✅ feature_importance.png                        ║")
print("║     ✅ prediksi_vs_aktual.png                        ║")
print("║     ✅ realtime_dashboard.png                        ║")
print("╚══════════════════════════════════════════════════════╝")
print()

"""## 📌 Kesimpulan

### ✅ Apa yang Berhasil Dibangun?

1. **Pipeline ML end-to-end** — dari fetch data hingga prediksi real-time
2. **Feature Engineering** — 20+ indikator teknikal (SMA, EMA, RSI, MACD, Bollinger Bands, dll)
3. **Model XGBoost** — dengan hyperparameter yang dioptimasi untuk data saham
4. **Evaluasi komprehensif** — accuracy, confusion matrix, confidence score
5. **Realtime inference** — bisa diprediksi kapan saja dengan data terbaru
6. **Multi-stock training** — model yang lebih general

---

### 💡 Insight dari Hasil Model

- **RSI & MACD_Diff** biasanya masuk top feature importance — konfirmasi nilai teknikal analis
- **Return lag 1-3 hari** sangat informatif → ada momentum jangka pendek di saham IDX
- **Volume Ratio** penting — pergerakan harga dengan volume tinggi lebih reliable
- Model lebih akurat saat confidence **> 65%** — gunakan threshold ini di production

---

### 🚀 Pengembangan Selanjutnya (Roadmap)

| Fitur | Prioritas |
|-------|----------|
| Integrasi sentiment analysis berita saham | 🔴 High |
| LSTM untuk sequence modeling | 🔴 High |
| Backtesting strategi trading | 🟡 Medium |
| Dashboard web (Streamlit/FastAPI) | 🟡 Medium |
| Alert notifikasi Telegram | 🟢 Low |
| Prediksi multi-horizon (3/5/7 hari) | 🟢 Low |

---

### ⚠️ Disclaimer

> Notebook ini dibuat untuk tujuan **edukasi dan riset ilmiah** dalam konteks kompetisi dan pembelajaran Machine Learning.
>
> **Akurasi model saham tidak pernah sempurna.** Pasar saham dipengaruhi oleh banyak faktor eksternal yang tidak ada dalam data historis (berita, kebijakan pemerintah, sentimen global, dll).
>
> **BUKAN saran investasi.** Selalu lakukan riset mandiri sebelum mengambil keputusan investasi.

---

```
  ___                        _        _    ___
 |_ _|_ ____   ___  ___  __|_|  /\  |_|  |_  |
  | || '_ \ \ / / |/ __|/ __| | /  \ |  |  | |
  | || | | \ V /| | (__| |__| |/ /\ \| | |__| |
 |___|_| |_|\_/ |_|\___|\___| /_/  \_\_|  ___/
                                             
         Made with ❤️ for Hackathon
```
"""